/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { BaseResponse_boolean_ } from './models/BaseResponse_boolean_';
export type { BaseResponse_Contact_ } from './models/BaseResponse_Contact_';
export type { BaseResponse_ContactVO_ } from './models/BaseResponse_ContactVO_';
export type { BaseResponse_Examination_ } from './models/BaseResponse_Examination_';
export type { BaseResponse_ExaminationVO_ } from './models/BaseResponse_ExaminationVO_';
export type { BaseResponse_List_ExaminationQuestionVO_ } from './models/BaseResponse_List_ExaminationQuestionVO_';
export type { BaseResponse_LoginUserVO_ } from './models/BaseResponse_LoginUserVO_';
export type { BaseResponse_long_ } from './models/BaseResponse_long_';
export type { BaseResponse_Page_Contact_ } from './models/BaseResponse_Page_Contact_';
export type { BaseResponse_Page_ContactVO_ } from './models/BaseResponse_Page_ContactVO_';
export type { BaseResponse_Page_Examination_ } from './models/BaseResponse_Page_Examination_';
export type { BaseResponse_Page_ExaminationSubmitVO_ } from './models/BaseResponse_Page_ExaminationSubmitVO_';
export type { BaseResponse_Page_ExaminationVO_ } from './models/BaseResponse_Page_ExaminationVO_';
export type { BaseResponse_Page_Question_ } from './models/BaseResponse_Page_Question_';
export type { BaseResponse_Page_QuestionContact_ } from './models/BaseResponse_Page_QuestionContact_';
export type { BaseResponse_Page_QuestionContactVO_ } from './models/BaseResponse_Page_QuestionContactVO_';
export type { BaseResponse_Page_QuestionSubmitVO_ } from './models/BaseResponse_Page_QuestionSubmitVO_';
export type { BaseResponse_Page_QuestionVO_ } from './models/BaseResponse_Page_QuestionVO_';
export type { BaseResponse_Page_User_ } from './models/BaseResponse_Page_User_';
export type { BaseResponse_Page_UserVO_ } from './models/BaseResponse_Page_UserVO_';
export type { BaseResponse_Question_ } from './models/BaseResponse_Question_';
export type { BaseResponse_QuestionContact_ } from './models/BaseResponse_QuestionContact_';
export type { BaseResponse_QuestionVO_ } from './models/BaseResponse_QuestionVO_';
export type { BaseResponse_string_ } from './models/BaseResponse_string_';
export type { BaseResponse_User_ } from './models/BaseResponse_User_';
export type { BaseResponse_UserVO_ } from './models/BaseResponse_UserVO_';
export type { Contact } from './models/Contact';
export type { ContactAddRequest } from './models/ContactAddRequest';
export type { ContactQueryRequest } from './models/ContactQueryRequest';
export type { ContactVO } from './models/ContactVO';
export type { DeleteRequest } from './models/DeleteRequest';
export type { Examination } from './models/Examination';
export type { ExaminationAddRequest } from './models/ExaminationAddRequest';
export type { ExaminationEditRequest } from './models/ExaminationEditRequest';
export type { ExaminationQueryRequest } from './models/ExaminationQueryRequest';
export type { ExaminationQuestionAddRequest } from './models/ExaminationQuestionAddRequest';
export type { ExaminationQuestionQueryRequest } from './models/ExaminationQuestionQueryRequest';
export type { ExaminationQuestionUpdateRequest } from './models/ExaminationQuestionUpdateRequest';
export type { ExaminationQuestionVO } from './models/ExaminationQuestionVO';
export type { ExaminationSubmitAddRequest } from './models/ExaminationSubmitAddRequest';
export type { ExaminationSubmitQueryRequest } from './models/ExaminationSubmitQueryRequest';
export type { ExaminationSubmitVO } from './models/ExaminationSubmitVO';
export type { ExaminationUpdateRequest } from './models/ExaminationUpdateRequest';
export type { ExaminationVO } from './models/ExaminationVO';
export type { JudgeCase } from './models/JudgeCase';
export type { JudgeConfig } from './models/JudgeConfig';
export type { JudgeInfo } from './models/JudgeInfo';
export type { LoginUserVO } from './models/LoginUserVO';
export type { OrderItem } from './models/OrderItem';
export type { Page_Contact_ } from './models/Page_Contact_';
export type { Page_ContactVO_ } from './models/Page_ContactVO_';
export type { Page_Examination_ } from './models/Page_Examination_';
export type { Page_ExaminationSubmitVO_ } from './models/Page_ExaminationSubmitVO_';
export type { Page_ExaminationVO_ } from './models/Page_ExaminationVO_';
export type { Page_Question_ } from './models/Page_Question_';
export type { Page_QuestionContact_ } from './models/Page_QuestionContact_';
export type { Page_QuestionContactVO_ } from './models/Page_QuestionContactVO_';
export type { Page_QuestionSubmitVO_ } from './models/Page_QuestionSubmitVO_';
export type { Page_QuestionVO_ } from './models/Page_QuestionVO_';
export type { Page_User_ } from './models/Page_User_';
export type { Page_UserVO_ } from './models/Page_UserVO_';
export type { Question } from './models/Question';
export type { QuestionAddRequest } from './models/QuestionAddRequest';
export type { QuestionContact } from './models/QuestionContact';
export type { QuestionContactAddRequest } from './models/QuestionContactAddRequest';
export type { QuestionContactQueryRequest } from './models/QuestionContactQueryRequest';
export type { QuestionContactVO } from './models/QuestionContactVO';
export type { QuestionEditRequest } from './models/QuestionEditRequest';
export type { QuestionQueryRequest } from './models/QuestionQueryRequest';
export type { QuestionSubmit } from './models/QuestionSubmit';
export type { QuestionSubmitAddRequest } from './models/QuestionSubmitAddRequest';
export type { QuestionSubmitQueryRequest } from './models/QuestionSubmitQueryRequest';
export type { QuestionSubmitVO } from './models/QuestionSubmitVO';
export type { QuestionUpdateRequest } from './models/QuestionUpdateRequest';
export type { QuestionVO } from './models/QuestionVO';
export type { User } from './models/User';
export type { UserAddRequest } from './models/UserAddRequest';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserQueryRequest } from './models/UserQueryRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserUpdateMyRequest } from './models/UserUpdateMyRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { UserVO } from './models/UserVO';

export { ContactControllerService } from './services/ContactControllerService';
export { ExaminationControllerService } from './services/ExaminationControllerService';
export { FileControllerService } from './services/FileControllerService';
export { QuestionContactControllerService } from './services/QuestionContactControllerService';
export { QuestionControllerService } from './services/QuestionControllerService';
export { UserControllerService } from './services/UserControllerService';
